<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DataSync.Core\DataSync.Core.csproj" />
    <ProjectReference Include="..\DataSync.Scripting\DataSync.Scripting.csproj" />
    <ProjectReference Include="..\DataSync.Drivers.Abstractions\DataSync.Drivers.Abstractions.csproj" />
    <ProjectReference Include="..\DataSync.Drivers.MsSql\DataSync.Drivers.MsSql.csproj" />
    <ProjectReference Include="..\DataSync.Drivers.Postgres\DataSync.Drivers.Postgres.csproj" />
    <ProjectReference Include="..\DataSync.State\DataSync.State.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
