using System.Data.Common;
using DataSync.Core.Config;

namespace DataSync.Drivers.Abstractions;

/// <summary>Where a statement in a preview came from, which is the first thing an operator wants to
/// know about one they did not expect to see.</summary>
public enum PreviewOrigin
{
    /// <summary>Generated by the reader, staging provider or writer itself.</summary>
    BuiltIn,

    /// <summary>Written by an operator as raw SQL — a column transform, a source filter, a hook body.</summary>
    OperatorSql,

    /// <summary>Produced by a bound script.</summary>
    Script,
}

/// <summary>
/// One thing a pass would do, in the order it would do it.
/// </summary>
/// <param name="Stage">Which part of the pass this belongs to, for grouping.</param>
/// <param name="Title">What it is, in words.</param>
/// <param name="Sql">
/// The statement, or **null** for a step that generates no SQL — an in-process value or row transform
/// is C# running over rows and has no statement. Naming it and saying so is honest; inventing a
/// statement for it would not be.
/// </param>
/// <param name="Detail">Where it came from: which script, at which binding level, or a note about why
/// this step could not be described.</param>
public sealed record PreviewStatement(
    string Stage, string Title, string? Sql, PreviewOrigin Origin, string? Detail = null);

/// <summary>
/// Everything a pipeline component is given at run time, so that what it describes is built from the
/// same inputs as what it would run.
/// </summary>
/// <param name="Connection">Open, against this component's own side. Needed because a projection over
/// unmapped columns has to ask the catalog what the columns are — the same thing the metadata pickers
/// do on every interaction.</param>
/// <param name="PreviousWatermark">What the store holds for this mapping, so an incremental reader
/// describes the statement it would issue *next*, not a first-run one.</param>
public sealed record PreviewRequest(
    DbConnection Connection,
    SourceTableRef Source,
    TableRef Target,
    IReadOnlyList<ColumnMapping> ColumnMappings,
    IReadOnlyDictionary<string, string> Options,
    string? PreviousWatermark);

/// <summary>
/// A reader, staging provider or writer that can say what it would run without running it.
/// <para>
/// Implemented by the component itself rather than reconstructed by the caller, and that is the whole
/// design. Every statement builder here is already a pure function — that separation was made
/// repeatedly, for testability — so a preview *could* be assembled by calling them from outside. It
/// would also be a second place that decides which builder to call with which arguments, and the day
/// those two disagree the preview becomes a lie that looks authoritative.
/// </para>
/// <para>
/// Optional. A component that does not implement it is reported as not describing itself, which is a
/// smaller lie than omitting it: an operator can see there is a step they cannot preview.
/// </para>
/// </summary>
public interface IStatementPreview
{
    Task<IReadOnlyList<PreviewStatement>> DescribeAsync(PreviewRequest request, CancellationToken cancellationToken);
}
