using System.Data.Common;
using DataSync.Core.Config;
using DataSync.Drivers.Abstractions;
using DataSync.Core.Sql;

namespace DataSync.Drivers.Generic;

/// <summary>
/// The target-side facts a generic writer needs — mapped columns, primary key, whether a generated
/// column is being written explicitly — resolved from the catalog once, plus the SQL fragments built
/// from them.
/// <para>
/// Assumes the caller has already pointed the connection at the target's database.
/// </para>
/// </summary>
public sealed class TargetShape
{
    private TargetShape(
        TableRef target,
        SqlDialect dialect,
        IReadOnlyList<ColumnMetadata> columns,
        IReadOnlyList<string> mappedTargetColumns,
        bool requiresGeneratedColumnOverride)
    {
        Target = target;
        QuotedTarget = dialect.QualifyTable(target.Schema, target.Table);
        Columns = columns;
        MappedTargetColumns = mappedTargetColumns;
        PrimaryKeyColumns = columns.Where(c => c.IsPrimaryKey).Select(c => c.Name).ToList();
        RequiresGeneratedColumnOverride = requiresGeneratedColumnOverride;
        InsertColumnList = string.Join(", ", mappedTargetColumns.Select(dialect.QuoteIdentifier));
    }

    public TableRef Target { get; }
    public string QuotedTarget { get; }
    public IReadOnlyList<ColumnMetadata> Columns { get; }
    public IReadOnlyList<string> MappedTargetColumns { get; }
    public IReadOnlyList<string> PrimaryKeyColumns { get; }

    /// <summary>True when a mapped column is generated by the engine (IDENTITY, <c>GENERATED ALWAYS</c>,
    /// AUTO_INCREMENT), so an INSERT supplying it explicitly needs whatever that engine requires.
    /// Detected from the catalog rather than declared in config — the failure mode otherwise is a run
    /// that errors out at apply time on a table the operator had no reason to think was special.</summary>
    public bool RequiresGeneratedColumnOverride { get; }

    public string InsertColumnList { get; }

    public static async Task<TargetShape> LoadAsync(
        SqlDialect dialect,
        ITableCatalog catalog,
        DbConnection targetConnection,
        TableRef target,
        IReadOnlyList<ColumnMapping> columnMappings,
        CancellationToken cancellationToken)
    {
        var columns = await catalog.GetColumnsAsync(targetConnection, target.Schema, target.Table, cancellationToken);
        var byName = columns.ToDictionary(c => c.Name, StringComparer.OrdinalIgnoreCase);

        var mappedTargetColumns = columnMappings.Select(m => m.TargetColumn).Distinct().ToList();
        var unknown = mappedTargetColumns.Where(c => !byName.ContainsKey(c)).ToList();
        if (unknown.Count > 0)
            throw new InvalidOperationException(
                $"Target column(s) {string.Join(", ", unknown)} were not found on '{target.Schema}.{target.Table}'.");

        return new TargetShape(
            target, dialect, columns, mappedTargetColumns, mappedTargetColumns.Any(c => byName[c].IsIdentity));
    }
}
