<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataSync.Core\DataSync.Core.csproj" />
    <ProjectReference Include="..\DataSync.Drivers.Abstractions\DataSync.Drivers.Abstractions.csproj" />
    <ProjectReference Include="..\DataSync.Drivers.MsSql\DataSync.Drivers.MsSql.csproj" />
    <ProjectReference Include="..\DataSync.State\DataSync.State.csproj" />
  </ItemGroup>

</Project>
